# Generated by Django 3.2.16 on 2022-11-23 11:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('my_expense', '0003_alter_expense_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='profile',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='expense',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
