# Generated by Django 4.1.3 on 2022-12-26 13:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_expense', '0004_auto_20221123_1108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='expense_categories',
        ),
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=1, validators=[django.core.validators.MaxValueValidator(10, message='Too many categories')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='my_expense.profile'),
            preserve_default=False,
        ),
    ]
