# Generated by Django 4.1.3 on 2022-12-26 13:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_expense', '0005_remove_profile_expense_categories_category_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10, message='Categories order must be 1-10')]),
        ),
    ]
