# Generated by Django 4.1.3 on 2023-01-04 12:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('my_expense', '0007_alter_category_options_alter_category_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='timestamp',
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
