# Generated by Django 4.1.3 on 2023-01-11 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_expense', '0011_remove_expense_timestamp_expense_timestamp2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='timestamp2',
            new_name='timestamp',
        ),
    ]
