# Generated by Django 4.1.3 on 2023-01-25 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_expense', '0012_rename_timestamp2_expense_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='all_cat_expenses', to='my_expense.category'),
            preserve_default=False,
        ),
    ]
