# Generated by Django 4.1.3 on 2023-01-31 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_expense', '0014_profile_telegram_chat_id_alter_profile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='telegram_chat_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
